# Generated by Django 6.0.6 on 2026-06-07 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('detector_type', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('core', 'Core'), ('mobility', 'Mobility')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('estimated_calories_per_rep', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('estimated_calories_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('has_ai_detection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_sets', models.PositiveIntegerField(default=0)),
                ('actual_reps', models.PositiveIntegerField(default=0)),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0)),
                ('planned_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calories_burned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('posture_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('correct_reps', models.PositiveIntegerField(default=0)),
                ('incorrect_reps', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='PostureEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_seconds', models.DecimalField(decimal_places=3, max_digits=8)),
                ('posture_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issue_type', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('landmark_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_events', to='fitness.aimodelrun')),
                ('exercise_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_events', to='fitness.exerciselog')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_weeks', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_weight_loss_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_total_calorie_deficit', models.IntegerField()),
                ('daily_calorie_burn_target', models.IntegerField()),
                ('weekly_calorie_burn_target', models.IntegerField()),
                ('ai_summary', models.TextField()),
                ('warning_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='fitness.fitnessgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('week_number', models.PositiveIntegerField()),
                ('workout_date', models.DateField()),
                ('focus', models.CharField(choices=[('Full Body', 'Full Body'), ('Core', 'Core'), ('Lower Body', 'Lower Body'), ('Upper Body', 'Upper Body'), ('Cardio', 'Cardio'), ('Rest', 'Rest')], max_length=50)),
                ('planned_duration_minutes', models.PositiveIntegerField(default=30)),
                ('planned_calories', models.PositiveIntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='fitness.roadmap')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('roadmap', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapDayExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_sets', models.PositiveIntegerField()),
                ('planned_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=30)),
                ('planned_calories', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exercise_order', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('roadmap_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.roadmapday')),
            ],
            options={
                'ordering': ['exercise_order'],
            },
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='roadmap_day_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.roadmapdayexercise'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('total_calories_burned', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_posture_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('ai_camera', 'AI Camera'), ('manual', 'Manual')], default='ai_camera', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fitness.roadmapday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='fitness.workoutsession'),
        ),
        migrations.AddField(
            model_name='aimodelrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='fitness.workoutsession'),
        ),
        migrations.CreateModel(
            name='DailyCalorieSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_date', models.DateField()),
                ('planned_calories', models.PositiveIntegerField(default=0)),
                ('actual_calories_burned', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('workout_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_calorie_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-summary_date'],
                'unique_together': {('user', 'summary_date')},
            },
        ),
    ]
